### ISSUE TITLE
advancedMetal

### ISSUE THREAD

**Issue by adiif1** [wumix/Smart-Space#14]
```
Message: 
Undefined index: advancedMetal

File: 
/includes/classes/class.PlanetRessUpdate.php

Line: 55
URL: http://188.213.171.66/game.php
PHP-Version: 5.4.45-0+deb7u5
PHP-API: apache2handler
MySQL-Cleint-Version: 5.5.52

#0 /includes/classes/class.PlanetRessUpdate.php(55): errorHandler(8, 'Undefined index...', '/includ...', 55, Array)
#1 /includes/classes/class.PlanetRessUpdate.php(121): ResourceUpdate->CreateHash()
#2 /includes/classes/class.PlanetRessUpdate.php(103): ResourceUpdate->UpdateRessource(1481578374, true)
#3 /includes/pages/game/class.AbstractPage.php(18): ResourceUpdate->CalcResource()
#4 /includes/pages/game/class.ShowOverviewPage.php(35): AbstractPage->__construct()
#5 /game.php(51): ShowOverviewPage->__construct()
#6 {main}
```

**Comment by wumix** [comment]
Incomplete SQL upload to your phpmyadmin ore sql hosting..

Dont use the installer this is not working yet!
