### ISSUE TITLE
prem_time

### ISSUE THREAD

**Issue by adiif1** [wumix/Smart-Space#15]
```
Message: 
Undefined index: prem_time

File: 
/includes/pages/game/class.AbstractPage.php

Line: 108
URL: http://188.213.171.66/game.php
PHP-Version: 5.4.45-0+deb7u5
PHP-API: apache2handler
MySQL-Cleint-Version: 5.5.52

#0 /includes/pages/game/class.AbstractPage.php(108): errorHandler(8, 'Undefined index...', '/includ...', 108, Array)
#1 /includes/pages/game/class.AbstractPage.php(215): AbstractPage->getNavigationData()
#2 /includes/pages/game/class.AbstractPage.php(313): AbstractPage->getPageData()
#3 /includes/pages/game/class.ShowOverviewPage.php(277): AbstractPage->display('page.overview.d...')
#4 /game.php(67): ShowOverviewPage->show()
#5 {main}
```

**Comment by wumix** [comment]
Upload your SQL
